// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ibc/lightclients/avalanche/v1/avalanche.proto

package avalanche

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	types "github.com/cosmos/ibc-go/v7/modules/core/02-client/types"
	_ "github.com/cosmos/ibc-go/v7/modules/core/23-commitment/types"
	_ "github.com/cosmos/ics23/go"
	_ "google.golang.org/protobuf/types/known/durationpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ClientState defines the 14-avalanche client state
type ClientState struct {
	ChainId    string   `protobuf:"bytes,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	TrustLevel Fraction `protobuf:"bytes,2,opt,name=trust_level,json=trustLevel,proto3" json:"trust_level"`
	// duration of the period since the LastestTimestamp during which the
	// submitted headers are valid for upgrade
	TrustingPeriod time.Duration `protobuf:"bytes,3,opt,name=trusting_period,json=trustingPeriod,proto3,stdduration" json:"trusting_period"`
	// defines how much new (untrusted) header's Time can drift into the future.
	MaxClockDrift time.Duration `protobuf:"bytes,4,opt,name=max_clock_drift,json=maxClockDrift,proto3,stdduration" json:"max_clock_drift"`
	// Block height when the client was frozen due to a misbehaviour
	FrozenHeight types.Height `protobuf:"bytes,5,opt,name=frozen_height,json=frozenHeight,proto3" json:"frozen_height"`
	// the latest block height
	LatestHeight types.Height `protobuf:"bytes,6,opt,name=latest_height,json=latestHeight,proto3" json:"latest_height"`
	Proof        [][]byte     `protobuf:"bytes,7,rep,name=proof,proto3" json:"proof,omitempty"`
	// Path at which next upgraded client will be committed.
	// Each element corresponds to the key for a single CommitmentProof in the
	// chained proof. NOTE: ClientState must stored under
	// `{upgradePath}/{upgradeHeight}/clientState` ConsensusState must be stored
	// under `{upgradepath}/{upgradeHeight}/consensusState` For SDK chains using
	// the default upgrade module, upgrade_path should be []string{"upgrade",
	// "upgradedIBCState"}`
	UpgradePath string `protobuf:"bytes,8,opt,name=upgrade_path,json=upgradePath,proto3" json:"upgrade_path,omitempty"`
	// allow_update_after_expiry is deprecated
	AllowUpdateAfterExpiry bool `protobuf:"varint,9,opt,name=allow_update_after_expiry,json=allowUpdateAfterExpiry,proto3" json:"allow_update_after_expiry,omitempty"` // Deprecated: Do not use.
	// allow_update_after_misbehaviour is deprecated
	AllowUpdateAfterMisbehaviour bool `protobuf:"varint,10,opt,name=allow_update_after_misbehaviour,json=allowUpdateAfterMisbehaviour,proto3" json:"allow_update_after_misbehaviour,omitempty"` // Deprecated: Do not use.
}

func (m *ClientState) Reset()         { *m = ClientState{} }
func (m *ClientState) String() string { return proto.CompactTextString(m) }
func (*ClientState) ProtoMessage()    {}
func (*ClientState) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6cb131cf15aa1e1, []int{0}
}
func (m *ClientState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ClientState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ClientState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ClientState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientState.Merge(m, src)
}
func (m *ClientState) XXX_Size() int {
	return m.Size()
}
func (m *ClientState) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientState.DiscardUnknown(m)
}

var xxx_messageInfo_ClientState proto.InternalMessageInfo

// ConsensusState defines the consensus state from Tendermint.
type ConsensusState struct {
	// timestamp that corresponds to the block height in which the ConsensusState
	// was stored.
	Timestamp          time.Time    `protobuf:"bytes,1,opt,name=timestamp,proto3,stdtime" json:"timestamp"`
	StorageRoot        []byte       `protobuf:"bytes,2,opt,name=storage_root,json=storageRoot,proto3" json:"storage_root,omitempty"`
	SignedStorageRoot  []byte       `protobuf:"bytes,3,opt,name=signed_storage_root,json=signedStorageRoot,proto3" json:"signed_storage_root,omitempty"`
	ValidatorSet       []byte       `protobuf:"bytes,4,opt,name=validator_set,json=validatorSet,proto3" json:"validator_set,omitempty"`
	SignedValidatorSet []byte       `protobuf:"bytes,5,opt,name=signed_validator_set,json=signedValidatorSet,proto3" json:"signed_validator_set,omitempty"`
	Vdrs               []*Validator `protobuf:"bytes,6,rep,name=vdrs,proto3" json:"vdrs,omitempty"`
	SignersInput       []byte       `protobuf:"bytes,8,opt,name=signers_input,json=signersInput,proto3" json:"signers_input,omitempty"`
}

func (m *ConsensusState) Reset()         { *m = ConsensusState{} }
func (m *ConsensusState) String() string { return proto.CompactTextString(m) }
func (*ConsensusState) ProtoMessage()    {}
func (*ConsensusState) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6cb131cf15aa1e1, []int{1}
}
func (m *ConsensusState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ConsensusState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ConsensusState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ConsensusState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsensusState.Merge(m, src)
}
func (m *ConsensusState) XXX_Size() int {
	return m.Size()
}
func (m *ConsensusState) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsensusState.DiscardUnknown(m)
}

var xxx_messageInfo_ConsensusState proto.InternalMessageInfo

// Fraction defines the protobuf message type for tmmath.Fraction that only
// supports positive values.
type Fraction struct {
	Numerator   uint64 `protobuf:"varint,1,opt,name=numerator,proto3" json:"numerator,omitempty"`
	Denominator uint64 `protobuf:"varint,2,opt,name=denominator,proto3" json:"denominator,omitempty"`
}

func (m *Fraction) Reset()         { *m = Fraction{} }
func (m *Fraction) String() string { return proto.CompactTextString(m) }
func (*Fraction) ProtoMessage()    {}
func (*Fraction) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6cb131cf15aa1e1, []int{2}
}
func (m *Fraction) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Fraction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Fraction.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Fraction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Fraction.Merge(m, src)
}
func (m *Fraction) XXX_Size() int {
	return m.Size()
}
func (m *Fraction) XXX_DiscardUnknown() {
	xxx_messageInfo_Fraction.DiscardUnknown(m)
}

var xxx_messageInfo_Fraction proto.InternalMessageInfo

func (m *Fraction) GetNumerator() uint64 {
	if m != nil {
		return m.Numerator
	}
	return 0
}

func (m *Fraction) GetDenominator() uint64 {
	if m != nil {
		return m.Denominator
	}
	return 0
}

type Misbehaviour struct {
	// ClientID is deprecated
	ClientId string  `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"` // Deprecated: Do not use.
	Header1  *Header `protobuf:"bytes,2,opt,name=header_1,json=header1,proto3" json:"header_1,omitempty"`
	Header2  *Header `protobuf:"bytes,3,opt,name=header_2,json=header2,proto3" json:"header_2,omitempty"`
}

func (m *Misbehaviour) Reset()         { *m = Misbehaviour{} }
func (m *Misbehaviour) String() string { return proto.CompactTextString(m) }
func (*Misbehaviour) ProtoMessage()    {}
func (*Misbehaviour) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6cb131cf15aa1e1, []int{3}
}
func (m *Misbehaviour) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Misbehaviour) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Misbehaviour.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Misbehaviour) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Misbehaviour.Merge(m, src)
}
func (m *Misbehaviour) XXX_Size() int {
	return m.Size()
}
func (m *Misbehaviour) XXX_DiscardUnknown() {
	xxx_messageInfo_Misbehaviour.DiscardUnknown(m)
}

var xxx_messageInfo_Misbehaviour proto.InternalMessageInfo

type Header struct {
	SubnetHeader        *SubnetHeader `protobuf:"bytes,1,opt,name=subnet_header,json=subnetHeader,proto3" json:"subnet_header,omitempty"`
	PchainHeader        *SubnetHeader `protobuf:"bytes,2,opt,name=pchain_header,json=pchainHeader,proto3" json:"pchain_header,omitempty"`
	SubnetTrustedHeight *types.Height `protobuf:"bytes,3,opt,name=subnet_trusted_height,json=subnetTrustedHeight,proto3" json:"subnet_trusted_height,omitempty"`
	PchainTrustedHeight *types.Height `protobuf:"bytes,4,opt,name=pchain_trusted_height,json=pchainTrustedHeight,proto3" json:"pchain_trusted_height,omitempty"`
	StorageRoot         []byte        `protobuf:"bytes,5,opt,name=storage_root,json=storageRoot,proto3" json:"storage_root,omitempty"`
	SignedStorageRoot   []byte        `protobuf:"bytes,6,opt,name=signed_storage_root,json=signedStorageRoot,proto3" json:"signed_storage_root,omitempty"`
	ValidatorSet        []byte        `protobuf:"bytes,7,opt,name=validator_set,json=validatorSet,proto3" json:"validator_set,omitempty"`
	SignedValidatorSet  []byte        `protobuf:"bytes,8,opt,name=signed_validator_set,json=signedValidatorSet,proto3" json:"signed_validator_set,omitempty"`
	Vdrs                []*Validator  `protobuf:"bytes,9,rep,name=vdrs,proto3" json:"vdrs,omitempty"`
	SignersInput        []byte        `protobuf:"bytes,10,opt,name=signers_input,json=signersInput,proto3" json:"signers_input,omitempty"`
}

func (m *Header) Reset()         { *m = Header{} }
func (m *Header) String() string { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()    {}
func (*Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6cb131cf15aa1e1, []int{4}
}
func (m *Header) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Header.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Header.Merge(m, src)
}
func (m *Header) XXX_Size() int {
	return m.Size()
}
func (m *Header) XXX_DiscardUnknown() {
	xxx_messageInfo_Header.DiscardUnknown(m)
}

var xxx_messageInfo_Header proto.InternalMessageInfo

func (m *Header) GetSubnetHeader() *SubnetHeader {
	if m != nil {
		return m.SubnetHeader
	}
	return nil
}

func (m *Header) GetPchainHeader() *SubnetHeader {
	if m != nil {
		return m.PchainHeader
	}
	return nil
}

func (m *Header) GetSubnetTrustedHeight() *types.Height {
	if m != nil {
		return m.SubnetTrustedHeight
	}
	return nil
}

func (m *Header) GetPchainTrustedHeight() *types.Height {
	if m != nil {
		return m.PchainTrustedHeight
	}
	return nil
}

func (m *Header) GetStorageRoot() []byte {
	if m != nil {
		return m.StorageRoot
	}
	return nil
}

func (m *Header) GetSignedStorageRoot() []byte {
	if m != nil {
		return m.SignedStorageRoot
	}
	return nil
}

func (m *Header) GetValidatorSet() []byte {
	if m != nil {
		return m.ValidatorSet
	}
	return nil
}

func (m *Header) GetSignedValidatorSet() []byte {
	if m != nil {
		return m.SignedValidatorSet
	}
	return nil
}

func (m *Header) GetVdrs() []*Validator {
	if m != nil {
		return m.Vdrs
	}
	return nil
}

func (m *Header) GetSignersInput() []byte {
	if m != nil {
		return m.SignersInput
	}
	return nil
}

type SubnetHeader struct {
	Height    *types.Height `protobuf:"bytes,1,opt,name=height,proto3" json:"height,omitempty"`
	Timestamp time.Time     `protobuf:"bytes,2,opt,name=timestamp,proto3,stdtime" json:"timestamp"`
	BlockHash []byte        `protobuf:"bytes,3,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
}

func (m *SubnetHeader) Reset()         { *m = SubnetHeader{} }
func (m *SubnetHeader) String() string { return proto.CompactTextString(m) }
func (*SubnetHeader) ProtoMessage()    {}
func (*SubnetHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6cb131cf15aa1e1, []int{5}
}
func (m *SubnetHeader) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SubnetHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SubnetHeader.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SubnetHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubnetHeader.Merge(m, src)
}
func (m *SubnetHeader) XXX_Size() int {
	return m.Size()
}
func (m *SubnetHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_SubnetHeader.DiscardUnknown(m)
}

var xxx_messageInfo_SubnetHeader proto.InternalMessageInfo

func (m *SubnetHeader) GetHeight() *types.Height {
	if m != nil {
		return m.Height
	}
	return nil
}

func (m *SubnetHeader) GetTimestamp() time.Time {
	if m != nil {
		return m.Timestamp
	}
	return time.Time{}
}

func (m *SubnetHeader) GetBlockHash() []byte {
	if m != nil {
		return m.BlockHash
	}
	return nil
}

type Validator struct {
	PublicKeyByte []byte    `protobuf:"bytes,1,opt,name=public_key_byte,json=publicKeyByte,proto3" json:"public_key_byte,omitempty"`
	Weight        uint64    `protobuf:"varint,3,opt,name=weight,proto3" json:"weight,omitempty"`
	NodeIDs       [][]byte  `protobuf:"bytes,4,rep,name=nodeIDs,proto3" json:"nodeIDs,omitempty"`
	EndTime       time.Time `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3,stdtime" json:"end_time"`
}

func (m *Validator) Reset()         { *m = Validator{} }
func (m *Validator) String() string { return proto.CompactTextString(m) }
func (*Validator) ProtoMessage()    {}
func (*Validator) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6cb131cf15aa1e1, []int{6}
}
func (m *Validator) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Validator) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Validator.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Validator) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Validator.Merge(m, src)
}
func (m *Validator) XXX_Size() int {
	return m.Size()
}
func (m *Validator) XXX_DiscardUnknown() {
	xxx_messageInfo_Validator.DiscardUnknown(m)
}

var xxx_messageInfo_Validator proto.InternalMessageInfo

func (m *Validator) GetPublicKeyByte() []byte {
	if m != nil {
		return m.PublicKeyByte
	}
	return nil
}

func (m *Validator) GetWeight() uint64 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *Validator) GetNodeIDs() [][]byte {
	if m != nil {
		return m.NodeIDs
	}
	return nil
}

func (m *Validator) GetEndTime() time.Time {
	if m != nil {
		return m.EndTime
	}
	return time.Time{}
}

type MerkleKey struct {
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
}

func (m *MerkleKey) Reset()         { *m = MerkleKey{} }
func (m *MerkleKey) String() string { return proto.CompactTextString(m) }
func (*MerkleKey) ProtoMessage()    {}
func (*MerkleKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_d6cb131cf15aa1e1, []int{7}
}
func (m *MerkleKey) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MerkleKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MerkleKey.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MerkleKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MerkleKey.Merge(m, src)
}
func (m *MerkleKey) XXX_Size() int {
	return m.Size()
}
func (m *MerkleKey) XXX_DiscardUnknown() {
	xxx_messageInfo_MerkleKey.DiscardUnknown(m)
}

var xxx_messageInfo_MerkleKey proto.InternalMessageInfo

func (m *MerkleKey) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func init() {
	proto.RegisterType((*ClientState)(nil), "ibc.lightclients.avalanche.v1.ClientState")
	proto.RegisterType((*ConsensusState)(nil), "ibc.lightclients.avalanche.v1.ConsensusState")
	proto.RegisterType((*Fraction)(nil), "ibc.lightclients.avalanche.v1.Fraction")
	proto.RegisterType((*Misbehaviour)(nil), "ibc.lightclients.avalanche.v1.Misbehaviour")
	proto.RegisterType((*Header)(nil), "ibc.lightclients.avalanche.v1.Header")
	proto.RegisterType((*SubnetHeader)(nil), "ibc.lightclients.avalanche.v1.SubnetHeader")
	proto.RegisterType((*Validator)(nil), "ibc.lightclients.avalanche.v1.Validator")
	proto.RegisterType((*MerkleKey)(nil), "ibc.lightclients.avalanche.v1.MerkleKey")
}

func init() {
	proto.RegisterFile("ibc/lightclients/avalanche/v1/avalanche.proto", fileDescriptor_d6cb131cf15aa1e1)
}

var fileDescriptor_d6cb131cf15aa1e1 = []byte{
	// 1073 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0x4d, 0x6f, 0xdb, 0x46,
	0x13, 0x36, 0x25, 0x59, 0x1f, 0x2b, 0x3a, 0x79, 0xdf, 0x8d, 0x13, 0xd0, 0x86, 0x2d, 0xa9, 0x2a,
	0xda, 0x08, 0x28, 0x4c, 0x55, 0x4a, 0x81, 0x02, 0xfd, 0x40, 0x51, 0xd9, 0x29, 0xec, 0x3a, 0x36,
	0x0c, 0x3a, 0xed, 0xa1, 0x17, 0x62, 0x49, 0xae, 0xc5, 0x85, 0x49, 0x2e, 0xc1, 0x5d, 0x2a, 0x56,
	0x7f, 0x41, 0x8f, 0x39, 0xf6, 0xd8, 0x4b, 0xfb, 0x5b, 0x72, 0x0c, 0xd0, 0x4b, 0x7b, 0x49, 0x0b,
	0xfb, 0x50, 0xa0, 0xbf, 0xa2, 0xd8, 0x0f, 0x4a, 0xb2, 0x5b, 0x54, 0x4e, 0xd0, 0xdb, 0xce, 0xec,
	0xf3, 0x3c, 0xdc, 0x99, 0x9d, 0x19, 0x2e, 0xd8, 0x21, 0x9e, 0xdf, 0x8f, 0xc8, 0x38, 0xe4, 0x7e,
	0x44, 0x70, 0xc2, 0x59, 0x1f, 0x4d, 0x50, 0x84, 0x12, 0x3f, 0xc4, 0xfd, 0xc9, 0x60, 0x6e, 0xd8,
	0x69, 0x46, 0x39, 0x85, 0xdb, 0xc4, 0xf3, 0xed, 0x45, 0xb8, 0x3d, 0x47, 0x4c, 0x06, 0x9b, 0xeb,
	0x63, 0x3a, 0xa6, 0x12, 0xd9, 0x17, 0x2b, 0x45, 0xda, 0x6c, 0x8d, 0x29, 0x1d, 0x47, 0xb8, 0x2f,
	0x2d, 0x2f, 0x3f, 0xeb, 0x07, 0x79, 0x86, 0x38, 0xa1, 0x89, 0xde, 0xdf, 0xf2, 0x29, 0x8b, 0x29,
	0xeb, 0x13, 0x9f, 0x0d, 0x1f, 0x89, 0xaf, 0xa6, 0x19, 0xa5, 0x67, 0x4c, 0xef, 0xb6, 0xc5, 0x09,
	0x7d, 0x9a, 0xe1, 0xbe, 0xfa, 0xa4, 0x00, 0xa8, 0x55, 0x01, 0xb8, 0x29, 0xcf, 0x49, 0x8c, 0x19,
	0x47, 0x71, 0xaa, 0x01, 0x0f, 0xe7, 0x0a, 0x34, 0x8e, 0x09, 0x8f, 0x0b, 0x95, 0x99, 0xa5, 0x80,
	0xdd, 0x3f, 0x2b, 0xa0, 0xb9, 0x2b, 0xa5, 0x4f, 0x39, 0xe2, 0x18, 0x6e, 0x80, 0xba, 0x1f, 0x22,
	0x92, 0xb8, 0x24, 0xb0, 0x8c, 0x8e, 0xd1, 0x6b, 0x38, 0x35, 0x69, 0x1f, 0x04, 0xf0, 0x18, 0x34,
	0x79, 0x96, 0x33, 0xee, 0x46, 0x78, 0x82, 0x23, 0xab, 0xd4, 0x31, 0x7a, 0xcd, 0xe1, 0x43, 0xfb,
	0x5f, 0xd3, 0x63, 0x7f, 0x91, 0x21, 0x5f, 0xc4, 0x3d, 0xaa, 0xbc, 0x78, 0xd5, 0x5e, 0x71, 0x80,
	0x54, 0x78, 0x22, 0x04, 0xe0, 0x13, 0x70, 0x57, 0x5a, 0x24, 0x19, 0xbb, 0x29, 0xce, 0x08, 0x0d,
	0xac, 0xb2, 0xd4, 0xdc, 0xb0, 0x55, 0x78, 0x76, 0x11, 0x9e, 0xbd, 0xa7, 0xb3, 0x37, 0xaa, 0x0b,
	0x95, 0xef, 0x7f, 0x6b, 0x1b, 0xce, 0x9d, 0x82, 0x7b, 0x22, 0xa9, 0xf0, 0x10, 0xdc, 0x8d, 0xd1,
	0x85, 0xeb, 0x47, 0xd4, 0x3f, 0x77, 0x83, 0x8c, 0x9c, 0x71, 0xab, 0x72, 0x7b, 0xb5, 0xb5, 0x18,
	0x5d, 0xec, 0x0a, 0xea, 0x9e, 0x60, 0xc2, 0xc7, 0x60, 0xed, 0x2c, 0xa3, 0xdf, 0xe2, 0xc4, 0x0d,
	0xb1, 0x08, 0xcd, 0x5a, 0x95, 0x52, 0x9b, 0x32, 0x58, 0x91, 0x56, 0x5b, 0x5f, 0xc7, 0x64, 0x60,
	0xef, 0x4b, 0x84, 0x8e, 0xcf, 0x54, 0x34, 0xe5, 0x13, 0x32, 0x11, 0xe2, 0x98, 0xf1, 0x42, 0xa6,
	0x7a, 0x5b, 0x19, 0x45, 0xd3, 0x32, 0xeb, 0x60, 0x55, 0x96, 0x87, 0x55, 0xeb, 0x94, 0x7b, 0xa6,
	0xa3, 0x0c, 0xf8, 0x16, 0x30, 0xf3, 0x74, 0x9c, 0xa1, 0x00, 0xbb, 0x29, 0xe2, 0xa1, 0x55, 0x97,
	0xb7, 0xd5, 0xd4, 0xbe, 0x13, 0xc4, 0x43, 0xf8, 0x29, 0xd8, 0x40, 0x51, 0x44, 0x9f, 0xb9, 0x79,
	0x1a, 0x20, 0x8e, 0x5d, 0x74, 0xc6, 0x71, 0xe6, 0xe2, 0x8b, 0x94, 0x64, 0x53, 0xab, 0xd1, 0x31,
	0x7a, 0xf5, 0x51, 0xc9, 0x32, 0x9c, 0x07, 0x12, 0xf4, 0x95, 0xc4, 0x7c, 0x2e, 0x20, 0x8f, 0x25,
	0x02, 0x1e, 0x80, 0xf6, 0x3f, 0xd0, 0x63, 0xc2, 0x3c, 0x1c, 0xa2, 0x09, 0xa1, 0x79, 0x66, 0x81,
	0x99, 0xc8, 0xd6, 0x4d, 0x91, 0xa3, 0x05, 0xdc, 0x47, 0x95, 0xef, 0x7e, 0x68, 0xaf, 0x74, 0xff,
	0x28, 0x81, 0x3b, 0xbb, 0x34, 0x61, 0x38, 0x61, 0x39, 0x53, 0xf5, 0x36, 0x02, 0x8d, 0x59, 0xed,
	0xca, 0x82, 0x13, 0xe9, 0xb9, 0x79, 0x61, 0x4f, 0x0b, 0x84, 0xba, 0xb1, 0xe7, 0xe2, 0xc6, 0xe6,
	0x34, 0x91, 0x09, 0xc6, 0x69, 0x86, 0xc6, 0xd8, 0xcd, 0x28, 0xe5, 0xb2, 0x32, 0x4d, 0xa7, 0xa9,
	0x7d, 0x0e, 0xa5, 0x1c, 0xda, 0xe0, 0x1e, 0x23, 0xe3, 0x04, 0x07, 0xee, 0x35, 0x64, 0x59, 0x22,
	0xff, 0xaf, 0xb6, 0x4e, 0x17, 0xf0, 0x6f, 0x83, 0xb5, 0x09, 0x8a, 0x48, 0x80, 0x38, 0xcd, 0x5c,
	0x86, 0x55, 0x2d, 0x99, 0x8e, 0x39, 0x73, 0x9e, 0x62, 0x0e, 0xdf, 0x07, 0xeb, 0x5a, 0xf4, 0x3a,
	0x76, 0x55, 0x62, 0xa1, 0xda, 0xfb, 0x7a, 0x91, 0xf1, 0x09, 0xa8, 0x4c, 0x82, 0x8c, 0x59, 0xd5,
	0x4e, 0xb9, 0xd7, 0x1c, 0xf6, 0x96, 0xf4, 0xce, 0x8c, 0xea, 0x48, 0x96, 0x38, 0x94, 0xd4, 0xcc,
	0x98, 0x4b, 0x92, 0x34, 0xe7, 0xf2, 0xca, 0x4d, 0xc7, 0xd4, 0xce, 0x03, 0xe1, 0xd3, 0x99, 0xfe,
	0x12, 0xd4, 0x8b, 0xce, 0x83, 0x5b, 0xa0, 0x91, 0xe4, 0x31, 0xce, 0x84, 0x92, 0x4c, 0x71, 0xc5,
	0x99, 0x3b, 0x60, 0x07, 0x34, 0x03, 0x9c, 0xd0, 0x98, 0x24, 0x72, 0xbf, 0x24, 0xf7, 0x17, 0x5d,
	0xdd, 0x9f, 0x0d, 0x60, 0x2e, 0x5e, 0x26, 0x6c, 0x83, 0x86, 0x3a, 0xef, 0x6c, 0x48, 0xc8, 0x0a,
	0xa8, 0x2b, 0xe7, 0x41, 0x00, 0x8f, 0x40, 0x3d, 0xc4, 0x28, 0xc0, 0x99, 0x3b, 0xd0, 0x63, 0xe2,
	0x9d, 0x25, 0xa1, 0xee, 0x4b, 0xf8, 0xa8, 0x79, 0xf9, 0xaa, 0x5d, 0x53, 0xeb, 0x81, 0x53, 0x53,
	0x1a, 0x83, 0x05, 0xb9, 0xa1, 0x9e, 0x10, 0xaf, 0x2f, 0x37, 0x2c, 0xe4, 0x86, 0x3a, 0x43, 0xbf,
	0x56, 0x40, 0x55, 0x6d, 0xc1, 0x13, 0xb0, 0xc6, 0x72, 0x2f, 0xc1, 0xa2, 0x4d, 0x85, 0x43, 0xd7,
	0xe1, 0x7b, 0x4b, 0x3e, 0x72, 0x2a, 0x39, 0x4a, 0xc3, 0x31, 0xd9, 0x82, 0x25, 0x14, 0x53, 0x35,
	0x46, 0xb5, 0x62, 0xe9, 0x0d, 0x14, 0x95, 0x82, 0x56, 0x3c, 0x06, 0xf7, 0xf5, 0x19, 0xe5, 0xdc,
	0xc3, 0x41, 0x31, 0x52, 0xca, 0xcb, 0x46, 0x8a, 0x73, 0x4f, 0x11, 0x9f, 0x2a, 0x9e, 0x9e, 0x29,
	0xc7, 0xe0, 0xbe, 0x3e, 0xe1, 0x0d, 0xbd, 0xca, 0x72, 0x3d, 0x45, 0xbc, 0xae, 0x77, 0xb3, 0x07,
	0x57, 0x6f, 0xdd, 0x83, 0xd5, 0x5b, 0xf7, 0x60, 0xed, 0x35, 0x7a, 0xb0, 0xbe, 0xb4, 0x07, 0x1b,
	0xff, 0x4d, 0x0f, 0x82, 0xbf, 0xf7, 0x60, 0xf7, 0x47, 0x03, 0x98, 0x8b, 0x77, 0x09, 0x87, 0xa0,
	0xaa, 0xd3, 0x6b, 0x2c, 0x4d, 0xaf, 0x46, 0x5e, 0x9f, 0x8c, 0xa5, 0x37, 0x9b, 0x8c, 0xdb, 0x00,
	0x78, 0xf2, 0x87, 0x18, 0x22, 0x16, 0xea, 0x69, 0xd7, 0x90, 0x9e, 0x7d, 0xc4, 0xc2, 0xee, 0x4f,
	0x06, 0x68, 0xcc, 0x02, 0x84, 0xef, 0x82, 0xbb, 0x69, 0xee, 0x45, 0xc4, 0x77, 0xcf, 0xf1, 0xd4,
	0xf5, 0xa6, 0x1c, 0xcb, 0xd3, 0x9a, 0xce, 0x9a, 0x72, 0x1f, 0xe2, 0xe9, 0x68, 0xca, 0x31, 0x7c,
	0x00, 0xaa, 0xcf, 0xe6, 0xb5, 0x57, 0x71, 0xb4, 0x05, 0x2d, 0x50, 0x4b, 0x68, 0x80, 0x0f, 0xf6,
	0x98, 0x55, 0x91, 0x3f, 0xaa, 0xc2, 0x84, 0x9f, 0x81, 0x3a, 0x4e, 0x02, 0x57, 0x9c, 0x6b, 0xf6,
	0x27, 0xbd, 0x4d, 0x24, 0x35, 0x9c, 0x04, 0xc2, 0xdf, 0xdd, 0x06, 0x8d, 0x23, 0x9c, 0x9d, 0x47,
	0xf8, 0x10, 0x4f, 0xe1, 0xff, 0x40, 0xf9, 0x1c, 0x4f, 0xf5, 0xeb, 0x44, 0x2c, 0x47, 0xde, 0x8b,
	0xcb, 0x96, 0xf1, 0xf2, 0xb2, 0x65, 0xfc, 0x7e, 0xd9, 0x32, 0x9e, 0x5f, 0xb5, 0x56, 0x5e, 0x5e,
	0xb5, 0x56, 0x7e, 0xb9, 0x6a, 0xad, 0x7c, 0xb3, 0x3f, 0x26, 0x3c, 0xcc, 0x3d, 0xdb, 0xa7, 0x71,
	0xbf, 0x78, 0x72, 0x79, 0xfe, 0xce, 0x98, 0xf6, 0x27, 0x1f, 0xf6, 0x63, 0x1a, 0xe4, 0x11, 0x66,
	0xea, 0x2d, 0xb8, 0x53, 0x3c, 0x06, 0x07, 0x1f, 0xec, 0xcc, 0x2a, 0xe0, 0xe3, 0xd9, 0xca, 0xab,
	0xca, 0x93, 0x3e, 0xfa, 0x2b, 0x00, 0x00, 0xff, 0xff, 0xd6, 0x57, 0x69, 0x81, 0x3e, 0x0a, 0x00,
	0x00,
}

func (m *ClientState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ClientState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ClientState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.AllowUpdateAfterMisbehaviour {
		i--
		if m.AllowUpdateAfterMisbehaviour {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x50
	}
	if m.AllowUpdateAfterExpiry {
		i--
		if m.AllowUpdateAfterExpiry {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x48
	}
	if len(m.UpgradePath) > 0 {
		i -= len(m.UpgradePath)
		copy(dAtA[i:], m.UpgradePath)
		i = encodeVarintAvalanche(dAtA, i, uint64(len(m.UpgradePath)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.Proof) > 0 {
		for iNdEx := len(m.Proof) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Proof[iNdEx])
			copy(dAtA[i:], m.Proof[iNdEx])
			i = encodeVarintAvalanche(dAtA, i, uint64(len(m.Proof[iNdEx])))
			i--
			dAtA[i] = 0x3a
		}
	}
	{
		size, err := m.LatestHeight.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintAvalanche(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	{
		size, err := m.FrozenHeight.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintAvalanche(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	n3, err3 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.MaxClockDrift, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.MaxClockDrift):])
	if err3 != nil {
		return 0, err3
	}
	i -= n3
	i = encodeVarintAvalanche(dAtA, i, uint64(n3))
	i--
	dAtA[i] = 0x22
	n4, err4 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.TrustingPeriod, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.TrustingPeriod):])
	if err4 != nil {
		return 0, err4
	}
	i -= n4
	i = encodeVarintAvalanche(dAtA, i, uint64(n4))
	i--
	dAtA[i] = 0x1a
	{
		size, err := m.TrustLevel.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintAvalanche(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.ChainId) > 0 {
		i -= len(m.ChainId)
		copy(dAtA[i:], m.ChainId)
		i = encodeVarintAvalanche(dAtA, i, uint64(len(m.ChainId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ConsensusState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ConsensusState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ConsensusState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.SignersInput) > 0 {
		i -= len(m.SignersInput)
		copy(dAtA[i:], m.SignersInput)
		i = encodeVarintAvalanche(dAtA, i, uint64(len(m.SignersInput)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.Vdrs) > 0 {
		for iNdEx := len(m.Vdrs) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Vdrs[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintAvalanche(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.SignedValidatorSet) > 0 {
		i -= len(m.SignedValidatorSet)
		copy(dAtA[i:], m.SignedValidatorSet)
		i = encodeVarintAvalanche(dAtA, i, uint64(len(m.SignedValidatorSet)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.ValidatorSet) > 0 {
		i -= len(m.ValidatorSet)
		copy(dAtA[i:], m.ValidatorSet)
		i = encodeVarintAvalanche(dAtA, i, uint64(len(m.ValidatorSet)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.SignedStorageRoot) > 0 {
		i -= len(m.SignedStorageRoot)
		copy(dAtA[i:], m.SignedStorageRoot)
		i = encodeVarintAvalanche(dAtA, i, uint64(len(m.SignedStorageRoot)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.StorageRoot) > 0 {
		i -= len(m.StorageRoot)
		copy(dAtA[i:], m.StorageRoot)
		i = encodeVarintAvalanche(dAtA, i, uint64(len(m.StorageRoot)))
		i--
		dAtA[i] = 0x12
	}
	n6, err6 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.Timestamp, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.Timestamp):])
	if err6 != nil {
		return 0, err6
	}
	i -= n6
	i = encodeVarintAvalanche(dAtA, i, uint64(n6))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *Fraction) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Fraction) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Fraction) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Denominator != 0 {
		i = encodeVarintAvalanche(dAtA, i, uint64(m.Denominator))
		i--
		dAtA[i] = 0x10
	}
	if m.Numerator != 0 {
		i = encodeVarintAvalanche(dAtA, i, uint64(m.Numerator))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Misbehaviour) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Misbehaviour) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Misbehaviour) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Header2 != nil {
		{
			size, err := m.Header2.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintAvalanche(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.Header1 != nil {
		{
			size, err := m.Header1.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintAvalanche(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.ClientId) > 0 {
		i -= len(m.ClientId)
		copy(dAtA[i:], m.ClientId)
		i = encodeVarintAvalanche(dAtA, i, uint64(len(m.ClientId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Header) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Header) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Header) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.SignersInput) > 0 {
		i -= len(m.SignersInput)
		copy(dAtA[i:], m.SignersInput)
		i = encodeVarintAvalanche(dAtA, i, uint64(len(m.SignersInput)))
		i--
		dAtA[i] = 0x52
	}
	if len(m.Vdrs) > 0 {
		for iNdEx := len(m.Vdrs) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Vdrs[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintAvalanche(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x4a
		}
	}
	if len(m.SignedValidatorSet) > 0 {
		i -= len(m.SignedValidatorSet)
		copy(dAtA[i:], m.SignedValidatorSet)
		i = encodeVarintAvalanche(dAtA, i, uint64(len(m.SignedValidatorSet)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.ValidatorSet) > 0 {
		i -= len(m.ValidatorSet)
		copy(dAtA[i:], m.ValidatorSet)
		i = encodeVarintAvalanche(dAtA, i, uint64(len(m.ValidatorSet)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.SignedStorageRoot) > 0 {
		i -= len(m.SignedStorageRoot)
		copy(dAtA[i:], m.SignedStorageRoot)
		i = encodeVarintAvalanche(dAtA, i, uint64(len(m.SignedStorageRoot)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.StorageRoot) > 0 {
		i -= len(m.StorageRoot)
		copy(dAtA[i:], m.StorageRoot)
		i = encodeVarintAvalanche(dAtA, i, uint64(len(m.StorageRoot)))
		i--
		dAtA[i] = 0x2a
	}
	if m.PchainTrustedHeight != nil {
		{
			size, err := m.PchainTrustedHeight.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintAvalanche(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if m.SubnetTrustedHeight != nil {
		{
			size, err := m.SubnetTrustedHeight.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintAvalanche(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.PchainHeader != nil {
		{
			size, err := m.PchainHeader.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintAvalanche(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.SubnetHeader != nil {
		{
			size, err := m.SubnetHeader.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintAvalanche(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *SubnetHeader) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SubnetHeader) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SubnetHeader) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.BlockHash) > 0 {
		i -= len(m.BlockHash)
		copy(dAtA[i:], m.BlockHash)
		i = encodeVarintAvalanche(dAtA, i, uint64(len(m.BlockHash)))
		i--
		dAtA[i] = 0x1a
	}
	n13, err13 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.Timestamp, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.Timestamp):])
	if err13 != nil {
		return 0, err13
	}
	i -= n13
	i = encodeVarintAvalanche(dAtA, i, uint64(n13))
	i--
	dAtA[i] = 0x12
	if m.Height != nil {
		{
			size, err := m.Height.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintAvalanche(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Validator) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Validator) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Validator) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n15, err15 := github_com_cosmos_gogoproto_types.StdTimeMarshalTo(m.EndTime, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdTime(m.EndTime):])
	if err15 != nil {
		return 0, err15
	}
	i -= n15
	i = encodeVarintAvalanche(dAtA, i, uint64(n15))
	i--
	dAtA[i] = 0x2a
	if len(m.NodeIDs) > 0 {
		for iNdEx := len(m.NodeIDs) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.NodeIDs[iNdEx])
			copy(dAtA[i:], m.NodeIDs[iNdEx])
			i = encodeVarintAvalanche(dAtA, i, uint64(len(m.NodeIDs[iNdEx])))
			i--
			dAtA[i] = 0x22
		}
	}
	if m.Weight != 0 {
		i = encodeVarintAvalanche(dAtA, i, uint64(m.Weight))
		i--
		dAtA[i] = 0x18
	}
	if len(m.PublicKeyByte) > 0 {
		i -= len(m.PublicKeyByte)
		copy(dAtA[i:], m.PublicKeyByte)
		i = encodeVarintAvalanche(dAtA, i, uint64(len(m.PublicKeyByte)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MerkleKey) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MerkleKey) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MerkleKey) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Key) > 0 {
		i -= len(m.Key)
		copy(dAtA[i:], m.Key)
		i = encodeVarintAvalanche(dAtA, i, uint64(len(m.Key)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintAvalanche(dAtA []byte, offset int, v uint64) int {
	offset -= sovAvalanche(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ClientState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ChainId)
	if l > 0 {
		n += 1 + l + sovAvalanche(uint64(l))
	}
	l = m.TrustLevel.Size()
	n += 1 + l + sovAvalanche(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.TrustingPeriod)
	n += 1 + l + sovAvalanche(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.MaxClockDrift)
	n += 1 + l + sovAvalanche(uint64(l))
	l = m.FrozenHeight.Size()
	n += 1 + l + sovAvalanche(uint64(l))
	l = m.LatestHeight.Size()
	n += 1 + l + sovAvalanche(uint64(l))
	if len(m.Proof) > 0 {
		for _, b := range m.Proof {
			l = len(b)
			n += 1 + l + sovAvalanche(uint64(l))
		}
	}
	l = len(m.UpgradePath)
	if l > 0 {
		n += 1 + l + sovAvalanche(uint64(l))
	}
	if m.AllowUpdateAfterExpiry {
		n += 2
	}
	if m.AllowUpdateAfterMisbehaviour {
		n += 2
	}
	return n
}

func (m *ConsensusState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.Timestamp)
	n += 1 + l + sovAvalanche(uint64(l))
	l = len(m.StorageRoot)
	if l > 0 {
		n += 1 + l + sovAvalanche(uint64(l))
	}
	l = len(m.SignedStorageRoot)
	if l > 0 {
		n += 1 + l + sovAvalanche(uint64(l))
	}
	l = len(m.ValidatorSet)
	if l > 0 {
		n += 1 + l + sovAvalanche(uint64(l))
	}
	l = len(m.SignedValidatorSet)
	if l > 0 {
		n += 1 + l + sovAvalanche(uint64(l))
	}
	if len(m.Vdrs) > 0 {
		for _, e := range m.Vdrs {
			l = e.Size()
			n += 1 + l + sovAvalanche(uint64(l))
		}
	}
	l = len(m.SignersInput)
	if l > 0 {
		n += 1 + l + sovAvalanche(uint64(l))
	}
	return n
}

func (m *Fraction) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Numerator != 0 {
		n += 1 + sovAvalanche(uint64(m.Numerator))
	}
	if m.Denominator != 0 {
		n += 1 + sovAvalanche(uint64(m.Denominator))
	}
	return n
}

func (m *Misbehaviour) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ClientId)
	if l > 0 {
		n += 1 + l + sovAvalanche(uint64(l))
	}
	if m.Header1 != nil {
		l = m.Header1.Size()
		n += 1 + l + sovAvalanche(uint64(l))
	}
	if m.Header2 != nil {
		l = m.Header2.Size()
		n += 1 + l + sovAvalanche(uint64(l))
	}
	return n
}

func (m *Header) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.SubnetHeader != nil {
		l = m.SubnetHeader.Size()
		n += 1 + l + sovAvalanche(uint64(l))
	}
	if m.PchainHeader != nil {
		l = m.PchainHeader.Size()
		n += 1 + l + sovAvalanche(uint64(l))
	}
	if m.SubnetTrustedHeight != nil {
		l = m.SubnetTrustedHeight.Size()
		n += 1 + l + sovAvalanche(uint64(l))
	}
	if m.PchainTrustedHeight != nil {
		l = m.PchainTrustedHeight.Size()
		n += 1 + l + sovAvalanche(uint64(l))
	}
	l = len(m.StorageRoot)
	if l > 0 {
		n += 1 + l + sovAvalanche(uint64(l))
	}
	l = len(m.SignedStorageRoot)
	if l > 0 {
		n += 1 + l + sovAvalanche(uint64(l))
	}
	l = len(m.ValidatorSet)
	if l > 0 {
		n += 1 + l + sovAvalanche(uint64(l))
	}
	l = len(m.SignedValidatorSet)
	if l > 0 {
		n += 1 + l + sovAvalanche(uint64(l))
	}
	if len(m.Vdrs) > 0 {
		for _, e := range m.Vdrs {
			l = e.Size()
			n += 1 + l + sovAvalanche(uint64(l))
		}
	}
	l = len(m.SignersInput)
	if l > 0 {
		n += 1 + l + sovAvalanche(uint64(l))
	}
	return n
}

func (m *SubnetHeader) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Height != nil {
		l = m.Height.Size()
		n += 1 + l + sovAvalanche(uint64(l))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.Timestamp)
	n += 1 + l + sovAvalanche(uint64(l))
	l = len(m.BlockHash)
	if l > 0 {
		n += 1 + l + sovAvalanche(uint64(l))
	}
	return n
}

func (m *Validator) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.PublicKeyByte)
	if l > 0 {
		n += 1 + l + sovAvalanche(uint64(l))
	}
	if m.Weight != 0 {
		n += 1 + sovAvalanche(uint64(m.Weight))
	}
	if len(m.NodeIDs) > 0 {
		for _, b := range m.NodeIDs {
			l = len(b)
			n += 1 + l + sovAvalanche(uint64(l))
		}
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdTime(m.EndTime)
	n += 1 + l + sovAvalanche(uint64(l))
	return n
}

func (m *MerkleKey) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Key)
	if l > 0 {
		n += 1 + l + sovAvalanche(uint64(l))
	}
	return n
}

func sovAvalanche(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozAvalanche(x uint64) (n int) {
	return sovAvalanche(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ClientState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAvalanche
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ClientState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ClientState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAvalanche
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAvalanche
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAvalanche
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChainId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TrustLevel", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAvalanche
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAvalanche
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAvalanche
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TrustLevel.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TrustingPeriod", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAvalanche
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAvalanche
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAvalanche
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.TrustingPeriod, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxClockDrift", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAvalanche
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAvalanche
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAvalanche
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.MaxClockDrift, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FrozenHeight", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAvalanche
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAvalanche
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAvalanche
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.FrozenHeight.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LatestHeight", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAvalanche
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAvalanche
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAvalanche
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.LatestHeight.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Proof", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAvalanche
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthAvalanche
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthAvalanche
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Proof = append(m.Proof, make([]byte, postIndex-iNdEx))
			copy(m.Proof[len(m.Proof)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UpgradePath", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAvalanche
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAvalanche
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAvalanche
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UpgradePath = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AllowUpdateAfterExpiry", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAvalanche
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.AllowUpdateAfterExpiry = bool(v != 0)
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AllowUpdateAfterMisbehaviour", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAvalanche
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.AllowUpdateAfterMisbehaviour = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipAvalanche(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAvalanche
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ConsensusState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAvalanche
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ConsensusState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ConsensusState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAvalanche
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAvalanche
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAvalanche
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.Timestamp, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StorageRoot", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAvalanche
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthAvalanche
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthAvalanche
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StorageRoot = append(m.StorageRoot[:0], dAtA[iNdEx:postIndex]...)
			if m.StorageRoot == nil {
				m.StorageRoot = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignedStorageRoot", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAvalanche
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthAvalanche
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthAvalanche
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SignedStorageRoot = append(m.SignedStorageRoot[:0], dAtA[iNdEx:postIndex]...)
			if m.SignedStorageRoot == nil {
				m.SignedStorageRoot = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorSet", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAvalanche
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthAvalanche
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthAvalanche
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorSet = append(m.ValidatorSet[:0], dAtA[iNdEx:postIndex]...)
			if m.ValidatorSet == nil {
				m.ValidatorSet = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignedValidatorSet", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAvalanche
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthAvalanche
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthAvalanche
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SignedValidatorSet = append(m.SignedValidatorSet[:0], dAtA[iNdEx:postIndex]...)
			if m.SignedValidatorSet == nil {
				m.SignedValidatorSet = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Vdrs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAvalanche
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAvalanche
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAvalanche
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Vdrs = append(m.Vdrs, &Validator{})
			if err := m.Vdrs[len(m.Vdrs)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignersInput", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAvalanche
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthAvalanche
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthAvalanche
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SignersInput = append(m.SignersInput[:0], dAtA[iNdEx:postIndex]...)
			if m.SignersInput == nil {
				m.SignersInput = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAvalanche(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAvalanche
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Fraction) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAvalanche
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Fraction: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Fraction: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Numerator", wireType)
			}
			m.Numerator = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAvalanche
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Numerator |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denominator", wireType)
			}
			m.Denominator = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAvalanche
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Denominator |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipAvalanche(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAvalanche
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Misbehaviour) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAvalanche
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Misbehaviour: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Misbehaviour: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClientId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAvalanche
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAvalanche
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAvalanche
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClientId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Header1", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAvalanche
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAvalanche
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAvalanche
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Header1 == nil {
				m.Header1 = &Header{}
			}
			if err := m.Header1.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Header2", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAvalanche
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAvalanche
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAvalanche
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Header2 == nil {
				m.Header2 = &Header{}
			}
			if err := m.Header2.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAvalanche(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAvalanche
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Header) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAvalanche
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Header: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Header: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubnetHeader", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAvalanche
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAvalanche
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAvalanche
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.SubnetHeader == nil {
				m.SubnetHeader = &SubnetHeader{}
			}
			if err := m.SubnetHeader.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PchainHeader", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAvalanche
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAvalanche
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAvalanche
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.PchainHeader == nil {
				m.PchainHeader = &SubnetHeader{}
			}
			if err := m.PchainHeader.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubnetTrustedHeight", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAvalanche
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAvalanche
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAvalanche
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.SubnetTrustedHeight == nil {
				m.SubnetTrustedHeight = &types.Height{}
			}
			if err := m.SubnetTrustedHeight.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PchainTrustedHeight", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAvalanche
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAvalanche
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAvalanche
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.PchainTrustedHeight == nil {
				m.PchainTrustedHeight = &types.Height{}
			}
			if err := m.PchainTrustedHeight.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StorageRoot", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAvalanche
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthAvalanche
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthAvalanche
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StorageRoot = append(m.StorageRoot[:0], dAtA[iNdEx:postIndex]...)
			if m.StorageRoot == nil {
				m.StorageRoot = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignedStorageRoot", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAvalanche
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthAvalanche
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthAvalanche
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SignedStorageRoot = append(m.SignedStorageRoot[:0], dAtA[iNdEx:postIndex]...)
			if m.SignedStorageRoot == nil {
				m.SignedStorageRoot = []byte{}
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorSet", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAvalanche
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthAvalanche
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthAvalanche
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorSet = append(m.ValidatorSet[:0], dAtA[iNdEx:postIndex]...)
			if m.ValidatorSet == nil {
				m.ValidatorSet = []byte{}
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignedValidatorSet", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAvalanche
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthAvalanche
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthAvalanche
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SignedValidatorSet = append(m.SignedValidatorSet[:0], dAtA[iNdEx:postIndex]...)
			if m.SignedValidatorSet == nil {
				m.SignedValidatorSet = []byte{}
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Vdrs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAvalanche
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAvalanche
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAvalanche
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Vdrs = append(m.Vdrs, &Validator{})
			if err := m.Vdrs[len(m.Vdrs)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignersInput", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAvalanche
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthAvalanche
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthAvalanche
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SignersInput = append(m.SignersInput[:0], dAtA[iNdEx:postIndex]...)
			if m.SignersInput == nil {
				m.SignersInput = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAvalanche(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAvalanche
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SubnetHeader) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAvalanche
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SubnetHeader: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SubnetHeader: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAvalanche
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAvalanche
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAvalanche
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Height == nil {
				m.Height = &types.Height{}
			}
			if err := m.Height.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAvalanche
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAvalanche
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAvalanche
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.Timestamp, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAvalanche
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthAvalanche
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthAvalanche
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BlockHash = append(m.BlockHash[:0], dAtA[iNdEx:postIndex]...)
			if m.BlockHash == nil {
				m.BlockHash = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAvalanche(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAvalanche
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Validator) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAvalanche
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Validator: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Validator: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PublicKeyByte", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAvalanche
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthAvalanche
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthAvalanche
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PublicKeyByte = append(m.PublicKeyByte[:0], dAtA[iNdEx:postIndex]...)
			if m.PublicKeyByte == nil {
				m.PublicKeyByte = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Weight", wireType)
			}
			m.Weight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAvalanche
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Weight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NodeIDs", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAvalanche
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthAvalanche
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthAvalanche
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NodeIDs = append(m.NodeIDs, make([]byte, postIndex-iNdEx))
			copy(m.NodeIDs[len(m.NodeIDs)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAvalanche
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAvalanche
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAvalanche
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdTimeUnmarshal(&m.EndTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAvalanche(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAvalanche
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MerkleKey) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAvalanche
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MerkleKey: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MerkleKey: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Key", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAvalanche
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAvalanche
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAvalanche
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Key = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAvalanche(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAvalanche
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipAvalanche(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowAvalanche
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAvalanche
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAvalanche
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthAvalanche
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupAvalanche
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthAvalanche
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthAvalanche        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowAvalanche          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupAvalanche = fmt.Errorf("proto: unexpected end of group")
)
